
package lt.viko.eif.atalalaite.webserviceclient.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "LibraryServiceImplService", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", wsdlLocation = "http://localhost:8090/libraryservice?wsdl")
public class LibraryServiceImplService
    extends Service
{

    private static final URL LIBRARYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private static final WebServiceException LIBRARYSERVICEIMPLSERVICE_EXCEPTION;
    private static final QName LIBRARYSERVICEIMPLSERVICE_QNAME = new QName("http://services.webservice.atalalaite.viko.eif.lt/", "LibraryServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/libraryservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRARYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        LIBRARYSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public LibraryServiceImplService() {
        super(__getWsdlLocation(), LIBRARYSERVICEIMPLSERVICE_QNAME);
    }

    public LibraryServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRARYSERVICEIMPLSERVICE_QNAME, features);
    }

    public LibraryServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, LIBRARYSERVICEIMPLSERVICE_QNAME);
    }

    public LibraryServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRARYSERVICEIMPLSERVICE_QNAME, features);
    }

    public LibraryServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LibraryServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LibraryService
     */
    @WebEndpoint(name = "LibraryServiceImplPort")
    public LibraryService getLibraryServiceImplPort() {
        return super.getPort(new QName("http://services.webservice.atalalaite.viko.eif.lt/", "LibraryServiceImplPort"), LibraryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LibraryService
     */
    @WebEndpoint(name = "LibraryServiceImplPort")
    public LibraryService getLibraryServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.webservice.atalalaite.viko.eif.lt/", "LibraryServiceImplPort"), LibraryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRARYSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw LIBRARYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return LIBRARYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
