
package lt.viko.eif.atalalaite.webserviceclient.services;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import lt.viko.eif.atalalaite.webserviceclient.model.Book;
import lt.viko.eif.atalalaite.webserviceclient.model.Exception_Exception;
import lt.viko.eif.atalalaite.webserviceclient.model.Library;
import lt.viko.eif.atalalaite.webserviceclient.model.ObjectFactory;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "LibraryService", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryService {


    /**
     * 
     * @return
     *     returns lt.viko.eif.atalalaite.webserviceclient.model.Library
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLibraryDetails", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.viko.eif.atalalaite.webserviceclient.model.GetLibraryDetails")
    @ResponseWrapper(localName = "getLibraryDetailsResponse", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.viko.eif.atalalaite.webserviceclient.model.GetLibraryDetailsResponse")
    @Action(input = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/getLibraryDetailsRequest", output = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/getLibraryDetailsResponse")
    public Library getLibraryDetails();

    /**
     * 
     * @param arg0
     * @return
     *     returns lt.viko.eif.atalalaite.webserviceclient.model.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookByIsbn", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.viko.eif.atalalaite.webserviceclient.model.GetBookByIsbn")
    @ResponseWrapper(localName = "getBookByIsbnResponse", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.viko.eif.atalalaite.webserviceclient.model.GetBookByIsbnResponse")
    @Action(input = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/getBookByIsbnRequest", output = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/getBookByIsbnResponse")
    public Book getBookByIsbn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeBook", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.viko.eif.atalalaite.webserviceclient.model.RemoveBook")
    @ResponseWrapper(localName = "removeBookResponse", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.viko.eif.atalalaite.webserviceclient.model.RemoveBookResponse")
    @Action(input = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/removeBookRequest", output = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/removeBookResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/removeBook/Fault/Exception")
    })
    public String removeBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addBook", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.viko.eif.atalalaite.webserviceclient.model.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.viko.eif.atalalaite.webserviceclient.model.AddBookResponse")
    @Action(input = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/addBookRequest", output = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/addBookResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/addBook/Fault/Exception")
    })
    public String addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0)
        throws Exception_Exception
    ;

}
