
package lt.eif.viko.atalalaite.webservice.client;

import jakarta.jws.WebMethod;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "LibraryService", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LibraryService {


    /**
     * 
     * @return
     *     returns lt.eif.viko.atalalaite.webservice.client.Library
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLibraryDetails", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.eif.viko.atalalaite.webservice.client.GetLibraryDetails")
    @ResponseWrapper(localName = "getLibraryDetailsResponse", targetNamespace = "http://services.webservice.atalalaite.viko.eif.lt/", className = "lt.eif.viko.atalalaite.webservice.client.GetLibraryDetailsResponse")
    @Action(input = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/getLibraryDetailsRequest", output = "http://services.webservice.atalalaite.viko.eif.lt/LibraryService/getLibraryDetailsResponse")
    public Library getLibraryDetails();

}
